### ISSUE TITLE
Error while generating PDF

### ISSUE THREAD

**Issue by ByteBaker** [geeky-anand/WaP-ToP#1]
The traceback says "a byte like object required, not 'str'"

I tried to read the code and it seems the list of files passed to the PDF generator function is in order, while images downloaded in the 'temp_images' folder have a few missing. This could be the probable cause.

**Comment by anandubey** [comment]
Issue fixed. The problem was with the image list generating function. The function now checks for the temp_images folder for the files and then sort it before returning.
